version: '3.8'

services:
  circuit-synth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circuit-synth
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./examples:/app/examples
      - ./tests:/app/tests
      # Mount output directory for generated files
      - ./output:/app/output
      # Mount cache directory for persistence
      - ./cache:/app/cache
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=info
    working_dir: /app
    command: python -c "import circuit_synth; print('Circuit Synth is ready!')"
    
  # Development service with interactive shell
  circuit-synth-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circuit-synth-dev
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples
      - ./tests:/app/tests
      - ./output:/app/output
      - ./cache:/app/cache
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=debug
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
    
  # Test service
  circuit-synth-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circuit-synth-test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./test_output:/app/test_output
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=info
    working_dir: /app
    command: python -m pytest tests/ -v 