services:
  # Circuit-Synth with KiCad via Docker platform emulation
  circuit-synth-kicad:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kicad-emulated
    container_name: circuit-synth-kicad-emulated
    volumes:
      - ../src:/app/src
      - ../examples:/app/examples
      - ../tests:/app/tests
      - ../output:/app/output
      - ../cache:/app/cache
      - ../kicad_projects:/app/kicad_projects
      - kicad_config:/home/circuit_synth/.config
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=info
      - KICAD_CONFIG_HOME=/home/circuit_synth/.config/kicad
      - KICAD_SYMBOL_DIR=/usr/share/kicad/symbols
      - KICAD_FOOTPRINT_DIR=/usr/share/kicad/footprints
      - KICAD_3DMODEL_DIR=/usr/share/kicad/3dmodels
    working_dir: /app
    command: >
      python -c "
      import circuit_synth; 
      import subprocess;
      import platform;
      print(f'Circuit Synth with KiCad (emulated on {platform.machine()}) is ready!');
      result = subprocess.run(['kicad-cli', 'version'], capture_output=True, text=True);
      print(f'KiCad CLI Version: {result.stdout.strip()}')
      "
    
  # Development service
  circuit-synth-kicad-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kicad-emulated
    container_name: circuit-synth-kicad-dev-emulated
    volumes:
      - ../src:/app/src
      - ../examples:/app/examples
      - ../tests:/app/tests
      - ../output:/app/output
      - ../cache:/app/cache
      - ../kicad_projects:/app/kicad_projects
      - kicad_config:/home/circuit_synth/.config
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=debug
      - KICAD_CONFIG_HOME=/home/circuit_synth/.config/kicad
      - KICAD_SYMBOL_DIR=/usr/share/kicad/symbols
      - KICAD_FOOTPRINT_DIR=/usr/share/kicad/footprints
      - KICAD_3DMODEL_DIR=/usr/share/kicad/3dmodels
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
    
  # Test service
  circuit-synth-kicad-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kicad-emulated  
    container_name: circuit-synth-kicad-test-emulated
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../test_output:/app/test_output
      - ../kicad_projects:/app/kicad_projects
    environment:
      - PYTHONPATH=/app/src
      - RUST_LOG=info
      - KICAD_CONFIG_HOME=/home/circuit_synth/.config/kicad
      - KICAD_SYMBOL_DIR=/usr/share/kicad/symbols
      - KICAD_FOOTPRINT_DIR=/usr/share/kicad/footprints
      - KICAD_3DMODEL_DIR=/usr/share/kicad/3dmodels
    working_dir: /app
    command: |
      bash -c "
        echo '=== Circuit-Synth + KiCad Emulated Integration Tests ==='
        echo 'Host Architecture:' && uname -m
        echo 'KiCad Version:' && kicad-cli version
        echo 'Library Check:'
        ls -la /usr/share/kicad/symbols/ | head -3
        ls -la /usr/share/kicad/footprints/ | head -3
        echo 'Circuit-Synth Test:'
        python -c 'import circuit_synth; print(\"✅ Circuit-Synth works\")'
        echo 'Running basic tests...'
        python -m pytest tests/unit/test_core_circuit.py -v -x || echo 'Some tests may fail in emulated environment'
      "

  # KiCad CLI utilities
  kicad-cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kicad-emulated
    container_name: kicad-cli-emulated
    volumes:
      - ../kicad_projects:/app/kicad_projects
      - ../output:/app/output
      - kicad_config:/home/circuit_synth/.config
    environment:
      - KICAD_CONFIG_HOME=/home/circuit_synth/.config/kicad
      - KICAD_SYMBOL_DIR=/usr/share/kicad/symbols
      - KICAD_FOOTPRINT_DIR=/usr/share/kicad/footprints
      - KICAD_3DMODEL_DIR=/usr/share/kicad/3dmodels
    working_dir: /app/kicad_projects
    entrypoint: ["kicad-cli"]

volumes:
  kicad_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/kicad_config

networks:
  default:
    name: circuit-synth-kicad-emulated-network