name: Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install KiCad
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt update
        sudo apt install --install-recommends kicad --yes
    
    - name: Verify KiCad Symbol Libraries
      run: |
        echo "📦 Verifying KiCad symbol libraries in repository..."
        echo "📁 Files in test data:"
        ls -la tests/test_data/kicad_symbols/
        echo "📋 Total files: $(find tests/test_data/kicad_symbols -name "*.kicad_sym" | wc -l)"

    - name: Install dependencies
      run: |
        uv sync --dev
        uv pip install -e ".[dev]"

    - name: Lint with flake8
      run: |
        uv run flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics --extend-ignore=F821
        uv run flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-ignore=F821

    - name: Type check with mypy
      run: echo "Type checking temporarily disabled - too many legacy type issues to resolve"

    - name: Format check with black
      run: uv run black --check src/

    - name: Import sort check with isort
      run: uv run isort --check-only src/

    - name: Debug KiCad Symbol Detection
      env:
        KICAD_SYMBOL_DIR: ${{ github.workspace }}/tests/test_data/kicad_symbols
      run: |
        echo "🔍 Debugging KiCad symbol detection..."
        echo "KICAD_SYMBOL_DIR environment variable: ${KICAD_SYMBOL_DIR:-'not set'}"
        echo "Checking test data path:"
        if [ -d "${KICAD_SYMBOL_DIR}" ]; then
            echo "✅ ${KICAD_SYMBOL_DIR} exists with $(find "${KICAD_SYMBOL_DIR}" -name "*.kicad_sym" 2>/dev/null | wc -l) symbol files"
            ls "${KICAD_SYMBOL_DIR}"/*.kicad_sym 2>/dev/null || echo "No .kicad_sym files found"
        else
            echo "❌ ${KICAD_SYMBOL_DIR} does not exist"
        fi
        
        # Test symbol cache directly
        echo "🧪 Testing symbol cache directly..."
        uv run python -c "
from circuit_synth.kicad.kicad_symbol_cache import SymbolLibCache
try:
    dirs = SymbolLibCache._find_kicad_symbol_dirs()
    print(f'Found KiCad symbol directories: {dirs}')
    if dirs:
        cache = SymbolLibCache()
        cache._build_complete_index()
        print(f'Built index with {len(cache._library_index)} libraries')
        print(f'Libraries found: {list(cache._library_index.keys())}')
        
        # Test loading a specific symbol
        data = SymbolLibCache.get_symbol_data('Device:R')
        print(f'✅ Successfully loaded Device:R with {len(data[\"pins\"])} pins')
    else:
        print('❌ No KiCad symbol directories found!')
except Exception as e:
    print(f'❌ Error: {e}')
    import traceback
    traceback.print_exc()
"

    - name: Run tests with pytest
      env:
        KICAD_SYMBOL_DIR: ${{ github.workspace }}/tests/test_data/kicad_symbols
      run: |
        uv run pytest --cov=circuit_synth --cov-report=xml --cov-report=term-missing -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false