name: Update Contributor Documentation

on:
  push:
    paths:
      - 'src/circuit_synth/claude_integration/agents/*.py'
      - 'src/circuit_synth/claude_integration/commands/*.py'
      - 'src/circuit_synth/claude_integration/agent_registry.py'
      - '.claude/**'
      - 'Contributors/**'
  pull_request:
    paths:
      - 'src/circuit_synth/claude_integration/agents/*.py'
      - 'src/circuit_synth/claude_integration/commands/*.py'
      - 'src/circuit_synth/claude_integration/agent_registry.py'
      - '.claude/**'
      - 'Contributors/**'

jobs:
  update-contributor-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
        
    - name: Check if Contributors docs need updates
      id: check_updates
      run: |
        echo "Checking if Contributors documentation needs updates..."
        python scripts/check_contributor_docs_sync.py
        echo "needs_update=$?" >> $GITHUB_OUTPUT
        
    - name: Update Contributors documentation
      if: steps.check_updates.outputs.needs_update == '1'
      run: |
        echo "Updating Contributors documentation..."
        python scripts/update_contributor_docs.py
        
    - name: Validate updated documentation
      if: steps.check_updates.outputs.needs_update == '1'
      run: |
        echo "Validating updated documentation..."
        python scripts/validate_contributor_docs.py
        
    - name: Check for documentation changes
      id: check_changes
      if: steps.check_updates.outputs.needs_update == '1'
      run: |
        if [[ -n $(git status --porcelain Contributors/) ]]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request for documentation updates
      if: steps.check_changes.outputs.changes_detected == 'true' && github.event_name == 'push'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          docs: Auto-update Contributors documentation
          
          - Updated agent and command documentation
          - Synchronized with latest code changes
          - Maintained consistency across all guides
          
          🤖 Generated automatically by contributor-docs workflow
        title: 'docs: Auto-update Contributors documentation'
        body: |
          ## 📚 Automatic Contributors Documentation Update
          
          This PR contains automatic updates to the Contributors documentation based on changes to agents, commands, or configuration.
          
          ### Changes Made
          - ✅ Updated Claude Code agents and commands reference
          - ✅ Synchronized documentation with code changes
          - ✅ Validated all documentation links and references
          - ✅ Maintained consistency across all contributor guides
          
          ### Validation
          - [x] All agent descriptions updated
          - [x] Command documentation current
          - [x] Usage examples validated
          - [x] Cross-references checked
          
          ### Review Notes
          Please review the changes to ensure:
          - Agent descriptions accurately reflect current capabilities
          - Command examples are up-to-date and functional
          - No sensitive information is exposed
          - Documentation style is consistent
          
          🤖 This PR was generated automatically by the contributor documentation workflow.
        branch: auto-update-contributor-docs
        delete-branch: true
        
    - name: Comment on PR with documentation status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const needsUpdate = '${{ steps.check_updates.outputs.needs_update }}' === '1';
          const changesDetected = '${{ steps.check_changes.outputs.changes_detected }}' === 'true';
          
          let message = '## 📚 Contributors Documentation Status\n\n';
          
          if (!needsUpdate) {
            message += '✅ **Contributors documentation is up-to-date**\n\n';
            message += 'No changes to agents, commands, or configuration detected that require documentation updates.';
          } else if (needsUpdate && !changesDetected) {
            message += '✅ **Contributors documentation updated successfully**\n\n';
            message += 'Documentation was automatically updated to reflect code changes, but no actual changes were needed.';
          } else {
            message += '⚠️ **Contributors documentation needs updates**\n\n';
            message += 'Changes to agents or commands were detected. Documentation updates will be committed automatically.';
          }
          
          message += '\n\n### Checked Files\n';
          message += '- Claude Code agents and commands reference\n';
          message += '- Development setup guides\n';
          message += '- Architecture documentation\n';
          message += '- Testing guidelines\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });