# Circuit Synth Unified Logging Configuration
# ============================================
# 
# This configuration file defines the unified logging system settings for Circuit Synth.
# It supports multiple environments (development, production, testing) and provides
# comprehensive logging capabilities including user tracking, performance monitoring,
# and LLM conversation logging.

logging:
  # Global logging level (TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Base directory for all log files
  log_directory: "logs"
  
  # Log message formats
  format:
    # Console format with colors and user context
    console: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{extra[component]: <10}</cyan> | <blue>{extra[user]: <12}</blue> | <yellow>{extra[session]: <8}</yellow> | {message}"
    
    # File format with full context information
    file: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {extra[component]: <10} | {extra[user]: <12} | {extra[session]: <8} | {extra[request_id]: <12} | {message}"
  
  # Logging sinks configuration
  sinks:
    # Console output (stderr)
    console:
      enabled: true
      level: "INFO"
      colorize: true
      filter_components: []  # Components to exclude from console
    
    # Main application log file
    main_file:
      enabled: true
      path: "logs/circuit_synth_{time:YYYY-MM-DD}.log"
      rotation: "100 MB"      # Rotate when file reaches 100MB
      retention: "30 days"    # Keep logs for 30 days
      compression: "gz"       # Compress rotated files
      level: "DEBUG"
      enqueue: true          # Enable async logging
    
    # Performance metrics log (JSON Lines format)
    performance_file:
      enabled: true
      path: "logs/performance_{time:YYYY-MM-DD}.jsonl"
      rotation: "50 MB"
      retention: "7 days"
      compression: "gz"
      level: "DEBUG"
      filter_type: "performance"
      enqueue: true
    
    # LLM conversation logs (JSON Lines format)
    llm_conversations:
      enabled: true
      path: "logs/llm_conversations_{time:YYYY-MM-DD}.jsonl"
      rotation: "200 MB"
      retention: "90 days"    # Keep LLM logs longer for analysis
      compression: "gz"
      level: "DEBUG"
      filter_type: "llm_conversation"
      enqueue: true
    
    # Error-only log file
    error_file:
      enabled: false          # Disabled by default, enabled in production
      path: "logs/errors_{time:YYYY-MM-DD}.log"
      rotation: "50 MB"
      retention: "90 days"
      compression: "gz"
      level: "ERROR"
      enqueue: true
  
  # Component-specific logging settings
  components:
    # LLM-related logging
    LLM:
      level: "INFO"
      include_prompt_content: true
      max_prompt_length: 1000
      log_response_content: true
      max_response_length: 1000
      track_costs: true
    
    # Rust component logging
    RUST:
      level: "INFO"
      forward_to_python: true
      include_function_names: true
    
    # Performance monitoring
    PERF:
      level: "DEBUG"
      enable_memory_tracking: true
      enable_cpu_tracking: false
      track_function_calls: true
    
    # Circuit generation
    CIRCUIT:
      level: "INFO"
      track_generation_steps: true
      include_component_details: true
    
    # KiCad integration
    KICAD:
      level: "INFO"
      track_file_operations: true
      include_schematic_details: true
    
    # Web interface
    WEB:
      level: "INFO"
      track_user_actions: true
      include_request_details: true
    
    # Authentication and security
    AUTH:
      level: "INFO"
      log_login_attempts: true
      log_permission_checks: true
      mask_sensitive_data: true
    
    # Database operations
    DATABASE:
      level: "INFO"
      log_queries: false      # Set to true for debugging
      track_performance: true
    
    # File operations
    FILES:
      level: "INFO"
      track_uploads: true
      track_downloads: true
      include_file_sizes: true
  
  # Multi-user support settings
  multi_user:
    enable_user_isolation: true
    session_timeout_hours: 24
    max_sessions_per_user: 10
    session_cleanup_interval_minutes: 60
    track_concurrent_users: true
  
  # Performance and optimization settings
  performance:
    async_logging: true
    buffer_size: 1000
    flush_interval_seconds: 5
    worker_threads: 2
    enable_compression: true
    batch_writes: true

# Environment-specific configuration overrides
environments:
  # Development environment settings
  development:
    logging:
      level: "DEBUG"
      
      format:
        console: "<green>{time:HH:mm:ss.SSS}</green> | <level>{level: <5}</level> | <cyan>{extra[component]: <8}</cyan> | <blue>{extra[user]: <10}</blue> | {message}"
      
      sinks:
        console:
          enabled: true
          level: "DEBUG"
          colorize: true
        
        main_file:
          path: "logs/dev_circuit_synth_{time:YYYY-MM-DD}.log"
          rotation: "10 MB"        # Smaller files for development
          retention: "3 days"      # Shorter retention
          level: "DEBUG"
        
        performance_file:
          path: "logs/dev_performance_{time:YYYY-MM-DD}.jsonl"
          rotation: "5 MB"
          retention: "1 day"
        
        llm_conversations:
          path: "logs/dev_llm_conversations_{time:YYYY-MM-DD}.jsonl"
          rotation: "20 MB"
          retention: "7 days"
      
      components:
        LLM:
          level: "DEBUG"
          include_prompt_content: true
          max_prompt_length: 2000    # Longer for debugging
        
        RUST:
          level: "DEBUG"
        
        PERF:
          level: "DEBUG"
          enable_memory_tracking: true
          enable_cpu_tracking: true
        
        DATABASE:
          log_queries: true          # Enable query logging in dev
      
      multi_user:
        session_timeout_hours: 8    # Shorter for development
        max_sessions_per_user: 5
      
      performance:
        async_logging: false        # Synchronous for easier debugging
        buffer_size: 100
        flush_interval_seconds: 1
        worker_threads: 1

  # Production environment settings
  production:
    logging:
      level: "INFO"
      
      sinks:
        console:
          enabled: false            # No console output in production
        
        main_file:
          path: "/var/log/circuit_synth/circuit_synth_{time:YYYY-MM-DD}.log"
          rotation: "100 MB"
          retention: "30 days"
          compression: "gz"
          level: "INFO"
        
        error_file:
          enabled: true
          path: "/var/log/circuit_synth/errors_{time:YYYY-MM-DD}.log"
          rotation: "50 MB"
          retention: "90 days"
          compression: "gz"
          level: "ERROR"
        
        performance_file:
          path: "/var/log/circuit_synth/performance_{time:YYYY-MM-DD}.jsonl"
          rotation: "50 MB"
          retention: "7 days"
          compression: "gz"
        
        llm_conversations:
          path: "/var/log/circuit_synth/llm_conversations_{time:YYYY-MM-DD}.jsonl"
          rotation: "200 MB"
          retention: "90 days"
          compression: "gz"
      
      components:
        LLM:
          level: "INFO"
          include_prompt_content: false  # Privacy in production
          max_prompt_length: 500
          log_response_content: false
        
        RUST:
          level: "INFO"
        
        PERF:
          level: "INFO"
          enable_memory_tracking: false  # Reduce overhead
          enable_cpu_tracking: false
        
        DATABASE:
          log_queries: false
      
      performance:
        async_logging: true
        buffer_size: 5000
        flush_interval_seconds: 5
        worker_threads: 4

  # Testing environment settings
  testing:
    logging:
      level: "DEBUG"
      
      sinks:
        console:
          enabled: true
          level: "DEBUG"
        
        main_file:
          path: "logs/test_circuit_synth_{time:YYYY-MM-DD}.log"
          rotation: "5 MB"
          retention: "1 day"
          level: "DEBUG"
        
        performance_file:
          enabled: false            # Disable performance logging in tests
        
        llm_conversations:
          enabled: false            # Disable LLM logging in tests
      
      components:
        LLM:
          level: "DEBUG"
          include_prompt_content: true
        
        DATABASE:
          log_queries: true
      
      performance:
        async_logging: false        # Synchronous for test reliability
        buffer_size: 50
        flush_interval_seconds: 1

# LLM cost tracking configuration
cost_tracking:
  enabled: true
  
  # Cost per 1K tokens for different providers and models
  providers:
    openai:
      gpt-4: 
        input: 0.03
        output: 0.06
      gpt-4-turbo:
        input: 0.01
        output: 0.03
      gpt-4-turbo-preview:
        input: 0.01
        output: 0.03
      gpt-3.5-turbo:
        input: 0.001
        output: 0.002
      gpt-3.5-turbo-16k:
        input: 0.003
        output: 0.004
    
    anthropic:
      claude-3-opus:
        input: 0.015
        output: 0.075
      claude-3-sonnet:
        input: 0.003
        output: 0.015
      claude-3-haiku:
        input: 0.00025
        output: 0.00125
      claude-2.1:
        input: 0.008
        output: 0.024
    
    google:
      gemini-pro:
        input: 0.001
        output: 0.002
      gemini-pro-vision:
        input: 0.002
        output: 0.004
    
    cohere:
      command:
        input: 0.001
        output: 0.002
      command-light:
        input: 0.0003
        output: 0.0006

# Security and privacy settings
security:
  log_sanitization:
    enabled: true
    sanitize_patterns:
      - "password"
      - "api_key"
      - "secret"
      - "token"
      - "auth"
      - "credential"
    replacement_text: "[REDACTED]"
  
  access_control:
    restrict_log_access: false     # Set to true in production
    allowed_users: []              # List of users who can access logs
    log_access_attempts: true

# Monitoring and alerting
monitoring:
  enabled: false                   # Enable in production
  
  thresholds:
    error_rate_per_minute: 10      # Alert if more than 10 errors/minute
    log_file_size_mb: 500          # Alert if log file exceeds 500MB
    disk_usage_percent: 85         # Alert if disk usage exceeds 85%
  
  alerts:
    email_recipients: []           # Email addresses for alerts
    webhook_url: null              # Webhook URL for alerts
    slack_channel: null            # Slack channel for alerts

# Retention and cleanup policies
retention:
  auto_cleanup: true
  cleanup_interval_hours: 24
  
  policies:
    debug_logs: "3 days"
    info_logs: "30 days"
    error_logs: "90 days"
    performance_logs: "7 days"
    llm_conversation_logs: "90 days"
    compressed_logs: "1 year"